"""Knowledge layer clients: datasheet RAG, compatibility matrix, failure
corpus, and skill pack fetch."""

from deepgent.knowledge.errata import ErrataScanResult, Erratum, scan_errata
from deepgent.knowledge.fact_confidence import (
    ArbitratedFact,
    ArbitrationReport,
    FactAssertion,
    arbitrate,
    arbitrate_all,
    confidence_for,
)
from deepgent.knowledge.hardware_check import (
    ConflictReport,
    HardwareConfig,
    Peripheral,
    Rail,
    check_conflicts,
    load_config,
)
from deepgent.knowledge.matrix import (
    Claim,
    Contradiction,
    MatrixAnalysis,
    Verdict,
    VerifyCandidate,
    analyze,
    detect_contradictions,
    hop_distance,
    next_to_verify,
    query,
)
from deepgent.knowledge.premortem import (
    PredictedRisk,
    PreMortem,
    assemble_premortem,
    premortem,
)
from deepgent.knowledge.products import (
    BomCandidate,
    BomConstraints,
    TriageResult,
    UpgradeReport,
    bom_advise,
    triage,
    upgrade_check,
)
from deepgent.knowledge.rag import (
    PROVENANCE_FIELDS,
    RagClient,
    build_knowledge_server,
    build_knowledge_tools,
    build_rag_client,
)
from deepgent.knowledge.skill_author import (
    SkillCandidate,
    cluster_tuples,
    draft_skill_candidates,
)
from deepgent.knowledge.skill_gate import (
    SkillIssue,
    blocking,
    render_report,
    validate_skills,
)
from deepgent.knowledge.skill_lifecycle import (
    AblationRecord,
    LifecycleReport,
    SkillMetric,
    analyze_lifecycle,
    evaluate_skills,
    load_ablation,
    load_ablation_file,
)
from deepgent.knowledge.skills import (
    SkillPack,
    default_skills_dir,
    list_skills,
    sync_skills,
)

__all__ = [
    "PROVENANCE_FIELDS",
    "AblationRecord",
    "ArbitratedFact",
    "ArbitrationReport",
    "BomCandidate",
    "BomConstraints",
    "Claim",
    "ConflictReport",
    "Contradiction",
    "ErrataScanResult",
    "Erratum",
    "FactAssertion",
    "HardwareConfig",
    "LifecycleReport",
    "MatrixAnalysis",
    "Peripheral",
    "PreMortem",
    "PredictedRisk",
    "RagClient",
    "Rail",
    "SkillCandidate",
    "SkillIssue",
    "SkillMetric",
    "SkillPack",
    "TriageResult",
    "UpgradeReport",
    "Verdict",
    "VerifyCandidate",
    "analyze",
    "analyze_lifecycle",
    "arbitrate",
    "arbitrate_all",
    "assemble_premortem",
    "blocking",
    "bom_advise",
    "build_knowledge_server",
    "build_knowledge_tools",
    "build_rag_client",
    "check_conflicts",
    "cluster_tuples",
    "confidence_for",
    "default_skills_dir",
    "detect_contradictions",
    "draft_skill_candidates",
    "evaluate_skills",
    "hop_distance",
    "list_skills",
    "load_ablation",
    "load_ablation_file",
    "load_config",
    "next_to_verify",
    "premortem",
    "query",
    "render_report",
    "scan_errata",
    "sync_skills",
    "triage",
    "upgrade_check",
    "validate_skills",
]
